/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiebeleidRouteImport } from './routes/cookiebeleid'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OverZadiassureRouteImport } from './routes/over-zadiassure'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacybeleidRouteImport } from './routes/privacybeleid'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VoorWieRouteImport } from './routes/voor-wie'
import { Route as AuthenticatedBeheerRouteImport } from './routes/_authenticated/beheer'
import { Route as AanpakSlugRouteImport } from './routes/aanpak.$slug'
import { Route as BegeleidingIndexRouteImport } from './routes/begeleiding.index'
import { Route as BegeleidingSlugRouteImport } from './routes/begeleiding.$slug'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmDocumentsRouteImport } from './routes/crm.documents'
import { Route as CrmTasksRouteImport } from './routes/crm.tasks'
import { Route as DocumentenIndexRouteImport } from './routes/documenten.index'
import { Route as DocumentenSlugRouteImport } from './routes/documenten.$slug'
import { Route as KenniscentrumIndexRouteImport } from './routes/kenniscentrum.index'
import { Route as KenniscentrumSlugRouteImport } from './routes/kenniscentrum.$slug'
import { Route as WetgevingIndexRouteImport } from './routes/wetgeving.index'
import { Route as WetgevingSlugRouteImport } from './routes/wetgeving.$slug'
import { Route as CrmCasesIndexRouteImport } from './routes/crm.cases.index'
import { Route as CrmCasesIdRouteImport } from './routes/crm.cases.$id'
import { Route as CrmClientsIndexRouteImport } from './routes/crm.clients.index'
import { Route as CrmClientsIdRouteImport } from './routes/crm.clients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiebeleidRoute = CookiebeleidRouteImport.update({
  id: '/cookiebeleid',
  path: '/cookiebeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OverZadiassureRoute = OverZadiassureRouteImport.update({
  id: '/over-zadiassure',
  path: '/over-zadiassure',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacybeleidRoute = PrivacybeleidRouteImport.update({
  id: '/privacybeleid',
  path: '/privacybeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorWieRoute = VoorWieRouteImport.update({
  id: '/voor-wie',
  path: '/voor-wie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBeheerRoute = AuthenticatedBeheerRouteImport.update({
  id: '/beheer',
  path: '/beheer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AanpakSlugRoute = AanpakSlugRouteImport.update({
  id: '/aanpak/$slug',
  path: '/aanpak/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BegeleidingIndexRoute = BegeleidingIndexRouteImport.update({
  id: '/begeleiding/',
  path: '/begeleiding/',
  getParentRoute: () => rootRouteImport,
} as any)
const BegeleidingSlugRoute = BegeleidingSlugRouteImport.update({
  id: '/begeleiding/$slug',
  path: '/begeleiding/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmDocumentsRoute = CrmDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTasksRoute = CrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CrmRoute,
} as any)
const DocumentenIndexRoute = DocumentenIndexRouteImport.update({
  id: '/documenten/',
  path: '/documenten/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentenSlugRoute = DocumentenSlugRouteImport.update({
  id: '/documenten/$slug',
  path: '/documenten/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KenniscentrumIndexRoute = KenniscentrumIndexRouteImport.update({
  id: '/kenniscentrum/',
  path: '/kenniscentrum/',
  getParentRoute: () => rootRouteImport,
} as any)
const KenniscentrumSlugRoute = KenniscentrumSlugRouteImport.update({
  id: '/kenniscentrum/$slug',
  path: '/kenniscentrum/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WetgevingIndexRoute = WetgevingIndexRouteImport.update({
  id: '/wetgeving/',
  path: '/wetgeving/',
  getParentRoute: () => rootRouteImport,
} as any)
const WetgevingSlugRoute = WetgevingSlugRouteImport.update({
  id: '/wetgeving/$slug',
  path: '/wetgeving/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCasesIndexRoute = CrmCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCasesIdRoute = CrmCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => CrmRoute,
} as any)
const CrmClientsIndexRoute = CrmClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmClientsIdRoute = CrmClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => CrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookiebeleid': typeof CookiebeleidRoute
  '/crm': typeof CrmRouteWithChildren
  '/faq': typeof FaqRoute
  '/over-zadiassure': typeof OverZadiassureRoute
  '/partners': typeof PartnersRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voor-wie': typeof VoorWieRoute
  '/beheer': typeof AuthenticatedBeheerRoute
  '/aanpak/$slug': typeof AanpakSlugRoute
  '/begeleiding/$slug': typeof BegeleidingSlugRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/documenten/$slug': typeof DocumentenSlugRoute
  '/kenniscentrum/$slug': typeof KenniscentrumSlugRoute
  '/wetgeving/$slug': typeof WetgevingSlugRoute
  '/begeleiding/': typeof BegeleidingIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/documenten/': typeof DocumentenIndexRoute
  '/kenniscentrum/': typeof KenniscentrumIndexRoute
  '/wetgeving/': typeof WetgevingIndexRoute
  '/crm/cases/$id': typeof CrmCasesIdRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/crm/cases/': typeof CrmCasesIndexRoute
  '/crm/clients/': typeof CrmClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookiebeleid': typeof CookiebeleidRoute
  '/faq': typeof FaqRoute
  '/over-zadiassure': typeof OverZadiassureRoute
  '/partners': typeof PartnersRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voor-wie': typeof VoorWieRoute
  '/beheer': typeof AuthenticatedBeheerRoute
  '/aanpak/$slug': typeof AanpakSlugRoute
  '/begeleiding/$slug': typeof BegeleidingSlugRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/documenten/$slug': typeof DocumentenSlugRoute
  '/kenniscentrum/$slug': typeof KenniscentrumSlugRoute
  '/wetgeving/$slug': typeof WetgevingSlugRoute
  '/begeleiding': typeof BegeleidingIndexRoute
  '/crm': typeof CrmIndexRoute
  '/documenten': typeof DocumentenIndexRoute
  '/kenniscentrum': typeof KenniscentrumIndexRoute
  '/wetgeving': typeof WetgevingIndexRoute
  '/crm/cases/$id': typeof CrmCasesIdRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/crm/cases': typeof CrmCasesIndexRoute
  '/crm/clients': typeof CrmClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookiebeleid': typeof CookiebeleidRoute
  '/crm': typeof CrmRouteWithChildren
  '/faq': typeof FaqRoute
  '/over-zadiassure': typeof OverZadiassureRoute
  '/partners': typeof PartnersRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voor-wie': typeof VoorWieRoute
  '/_authenticated/beheer': typeof AuthenticatedBeheerRoute
  '/aanpak/$slug': typeof AanpakSlugRoute
  '/begeleiding/$slug': typeof BegeleidingSlugRoute
  '/crm/documents': typeof CrmDocumentsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/documenten/$slug': typeof DocumentenSlugRoute
  '/kenniscentrum/$slug': typeof KenniscentrumSlugRoute
  '/wetgeving/$slug': typeof WetgevingSlugRoute
  '/begeleiding/': typeof BegeleidingIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/documenten/': typeof DocumentenIndexRoute
  '/kenniscentrum/': typeof KenniscentrumIndexRoute
  '/wetgeving/': typeof WetgevingIndexRoute
  '/crm/cases/$id': typeof CrmCasesIdRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/crm/cases/': typeof CrmCasesIndexRoute
  '/crm/clients/': typeof CrmClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algemene-voorwaarden'
    | '/auth'
    | '/contact'
    | '/cookiebeleid'
    | '/crm'
    | '/faq'
    | '/over-zadiassure'
    | '/partners'
    | '/privacybeleid'
    | '/sitemap.xml'
    | '/voor-wie'
    | '/beheer'
    | '/aanpak/$slug'
    | '/begeleiding/$slug'
    | '/crm/documents'
    | '/crm/tasks'
    | '/documenten/$slug'
    | '/kenniscentrum/$slug'
    | '/wetgeving/$slug'
    | '/begeleiding/'
    | '/crm/'
    | '/documenten/'
    | '/kenniscentrum/'
    | '/wetgeving/'
    | '/crm/cases/$id'
    | '/crm/clients/$id'
    | '/crm/cases/'
    | '/crm/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemene-voorwaarden'
    | '/auth'
    | '/contact'
    | '/cookiebeleid'
    | '/faq'
    | '/over-zadiassure'
    | '/partners'
    | '/privacybeleid'
    | '/sitemap.xml'
    | '/voor-wie'
    | '/beheer'
    | '/aanpak/$slug'
    | '/begeleiding/$slug'
    | '/crm/documents'
    | '/crm/tasks'
    | '/documenten/$slug'
    | '/kenniscentrum/$slug'
    | '/wetgeving/$slug'
    | '/begeleiding'
    | '/crm'
    | '/documenten'
    | '/kenniscentrum'
    | '/wetgeving'
    | '/crm/cases/$id'
    | '/crm/clients/$id'
    | '/crm/cases'
    | '/crm/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/algemene-voorwaarden'
    | '/auth'
    | '/contact'
    | '/cookiebeleid'
    | '/crm'
    | '/faq'
    | '/over-zadiassure'
    | '/partners'
    | '/privacybeleid'
    | '/sitemap.xml'
    | '/voor-wie'
    | '/_authenticated/beheer'
    | '/aanpak/$slug'
    | '/begeleiding/$slug'
    | '/crm/documents'
    | '/crm/tasks'
    | '/documenten/$slug'
    | '/kenniscentrum/$slug'
    | '/wetgeving/$slug'
    | '/begeleiding/'
    | '/crm/'
    | '/documenten/'
    | '/kenniscentrum/'
    | '/wetgeving/'
    | '/crm/cases/$id'
    | '/crm/clients/$id'
    | '/crm/cases/'
    | '/crm/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiebeleidRoute: typeof CookiebeleidRoute
  CrmRoute: typeof CrmRouteWithChildren
  FaqRoute: typeof FaqRoute
  OverZadiassureRoute: typeof OverZadiassureRoute
  PartnersRoute: typeof PartnersRoute
  PrivacybeleidRoute: typeof PrivacybeleidRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VoorWieRoute: typeof VoorWieRoute
  AanpakSlugRoute: typeof AanpakSlugRoute
  BegeleidingSlugRoute: typeof BegeleidingSlugRoute
  DocumentenSlugRoute: typeof DocumentenSlugRoute
  KenniscentrumSlugRoute: typeof KenniscentrumSlugRoute
  WetgevingSlugRoute: typeof WetgevingSlugRoute
  BegeleidingIndexRoute: typeof BegeleidingIndexRoute
  DocumentenIndexRoute: typeof DocumentenIndexRoute
  KenniscentrumIndexRoute: typeof KenniscentrumIndexRoute
  WetgevingIndexRoute: typeof WetgevingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookiebeleid': {
      id: '/cookiebeleid'
      path: '/cookiebeleid'
      fullPath: '/cookiebeleid'
      preLoaderRoute: typeof CookiebeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-zadiassure': {
      id: '/over-zadiassure'
      path: '/over-zadiassure'
      fullPath: '/over-zadiassure'
      preLoaderRoute: typeof OverZadiassureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacybeleid': {
      id: '/privacybeleid'
      path: '/privacybeleid'
      fullPath: '/privacybeleid'
      preLoaderRoute: typeof PrivacybeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-wie': {
      id: '/voor-wie'
      path: '/voor-wie'
      fullPath: '/voor-wie'
      preLoaderRoute: typeof VoorWieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/beheer': {
      id: '/_authenticated/beheer'
      path: '/beheer'
      fullPath: '/beheer'
      preLoaderRoute: typeof AuthenticatedBeheerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/aanpak/$slug': {
      id: '/aanpak/$slug'
      path: '/aanpak/$slug'
      fullPath: '/aanpak/$slug'
      preLoaderRoute: typeof AanpakSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begeleiding/': {
      id: '/begeleiding/'
      path: '/begeleiding'
      fullPath: '/begeleiding/'
      preLoaderRoute: typeof BegeleidingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begeleiding/$slug': {
      id: '/begeleiding/$slug'
      path: '/begeleiding/$slug'
      fullPath: '/begeleiding/$slug'
      preLoaderRoute: typeof BegeleidingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/documents': {
      id: '/crm/documents'
      path: '/documents'
      fullPath: '/crm/documents'
      preLoaderRoute: typeof CrmDocumentsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tasks': {
      id: '/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof CrmTasksRouteImport
      parentRoute: typeof CrmRoute
    }
    '/documenten/': {
      id: '/documenten/'
      path: '/documenten'
      fullPath: '/documenten/'
      preLoaderRoute: typeof DocumentenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documenten/$slug': {
      id: '/documenten/$slug'
      path: '/documenten/$slug'
      fullPath: '/documenten/$slug'
      preLoaderRoute: typeof DocumentenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenniscentrum/': {
      id: '/kenniscentrum/'
      path: '/kenniscentrum'
      fullPath: '/kenniscentrum/'
      preLoaderRoute: typeof KenniscentrumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenniscentrum/$slug': {
      id: '/kenniscentrum/$slug'
      path: '/kenniscentrum/$slug'
      fullPath: '/kenniscentrum/$slug'
      preLoaderRoute: typeof KenniscentrumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wetgeving/': {
      id: '/wetgeving/'
      path: '/wetgeving'
      fullPath: '/wetgeving/'
      preLoaderRoute: typeof WetgevingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wetgeving/$slug': {
      id: '/wetgeving/$slug'
      path: '/wetgeving/$slug'
      fullPath: '/wetgeving/$slug'
      preLoaderRoute: typeof WetgevingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/cases/': {
      id: '/crm/cases/'
      path: '/cases'
      fullPath: '/crm/cases/'
      preLoaderRoute: typeof CrmCasesIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/cases/$id': {
      id: '/crm/cases/$id'
      path: '/cases/$id'
      fullPath: '/crm/cases/$id'
      preLoaderRoute: typeof CrmCasesIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/clients/': {
      id: '/crm/clients/'
      path: '/clients'
      fullPath: '/crm/clients/'
      preLoaderRoute: typeof CrmClientsIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/clients/$id': {
      id: '/crm/clients/$id'
      path: '/clients/$id'
      fullPath: '/crm/clients/$id'
      preLoaderRoute: typeof CrmClientsIdRouteImport
      parentRoute: typeof CrmRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBeheerRoute: typeof AuthenticatedBeheerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBeheerRoute: AuthenticatedBeheerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CrmRouteChildren {
  CrmDocumentsRoute: typeof CrmDocumentsRoute
  CrmTasksRoute: typeof CrmTasksRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmCasesIdRoute: typeof CrmCasesIdRoute
  CrmClientsIdRoute: typeof CrmClientsIdRoute
  CrmCasesIndexRoute: typeof CrmCasesIndexRoute
  CrmClientsIndexRoute: typeof CrmClientsIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmDocumentsRoute: CrmDocumentsRoute,
  CrmTasksRoute: CrmTasksRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmCasesIdRoute: CrmCasesIdRoute,
  CrmClientsIdRoute: CrmClientsIdRoute,
  CrmCasesIndexRoute: CrmCasesIndexRoute,
  CrmClientsIndexRoute: CrmClientsIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiebeleidRoute: CookiebeleidRoute,
  CrmRoute: CrmRouteWithChildren,
  FaqRoute: FaqRoute,
  OverZadiassureRoute: OverZadiassureRoute,
  PartnersRoute: PartnersRoute,
  PrivacybeleidRoute: PrivacybeleidRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VoorWieRoute: VoorWieRoute,
  AanpakSlugRoute: AanpakSlugRoute,
  BegeleidingSlugRoute: BegeleidingSlugRoute,
  DocumentenSlugRoute: DocumentenSlugRoute,
  KenniscentrumSlugRoute: KenniscentrumSlugRoute,
  WetgevingSlugRoute: WetgevingSlugRoute,
  BegeleidingIndexRoute: BegeleidingIndexRoute,
  DocumentenIndexRoute: DocumentenIndexRoute,
  KenniscentrumIndexRoute: KenniscentrumIndexRoute,
  WetgevingIndexRoute: WetgevingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
